version: '3.9'

networks:
  grima_net:
    external: true

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_examen
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENCRYPTION_KEY=examen_grima_n8n_key
      - N8N_BASIC_AUTH_ACTIVE=true 
      - N8N_BASIC_AUTH_USER=admin 
      - N8N_BASIC_AUTH_PASSWORD=admin_pass
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
